@echo off

REM Executa o comando BCP e adiciona os dados sem sobrescrever o arquivo (modo append)
bcp "USE AC; SELECT 'Sigla' AS Sigla, 'Demontrativo' AS Demontrativo, 'Empresa' AS Empresa, 'NomeFantasia' AS NomeFantasia, 'SeqFolha' AS SeqFolha, 'CodEmpregado' AS CodEmpregado, 'NomeEmpregado' AS NomeEmpregado, 'CPF' AS CPF, 'Periodo' AS Periodo, 'TipoValor' AS TipoValor, 'TipoValorDescricao' AS TipoValorDescricao, 'Categoria' AS Categoria, 'ValorEsocial' AS ValorEsocial, 'ValorFortes' AS ValorFortes, 'CheckList' AS CheckList UNION SELECT 'HSCSL' as Sigla, 'IRRF' as Demontrativo, a.EMP_Codigo as Empresa, c.NmFantasia as NomeFantasia, a.Sequencial as SeqFolha, a.EPG_Codigo as CodEmpregado, b.Nome as NomeEmpregado, RIGHT(REPLICATE('0', 11) + CAST(a.CPF AS VARCHAR(11)), 11) AS CPF, a.PeriodoReferencia as Periodo, CAST(a.TipoValor AS VARCHAR) as TipoValor, '' as TipoValorDescricao, a.Categoria as Categoria, REPLACE(CAST(a.Valor AS VARCHAR), '.', ',') as ValorEsocial, REPLACE(CAST(a.ValorFortes AS VARCHAR), '.', ',') as ValorFortes, CASE WHEN a.Valor = a.ValorFortes THEN 'OK' WHEN a.Valor <> a.ValorFortes THEN 'DIFERENCA' END as CheckList FROM ES_IRRF_Demonstrativo a LEFT JOIN EPG b ON b.Codigo = a.EPG_Codigo AND b.EMP_Codigo = a.EMP_Codigo INNER JOIN EMP c ON c.Codigo = a.EMP_Codigo WHERE a.TipoValor IN ('31','32') AND a.PeriodoReferencia BETWEEN FORMAT(DATEADD(MONTH, -12, GETDATE()), 'yyyyMM') AND FORMAT(GETDATE(), 'yyyyMM') UNION SELECT 'HSCSL' as Sigla, 'INSS' as Demontrativo, a.EMP_Codigo as Empresa, c.NmFantasia as NomeFantasia, '' as SeqFolha, b.Codigo as CodEmpregado, b.Nome as NomeEmpregado, RIGHT(REPLICATE('0', 11) + CAST(a.CPF AS VARCHAR(11)), 11) AS CPF, a.PeriodoApuracao as Periodo, CAST(a.TipoValor AS VARCHAR) as TipoValor, CASE WHEN a.TipoValor = '21' THEN '21 - Valor total descontado do trabalhador para recolhimento à Previdência Social' END as TipoValorDescricao, a.Categoria as Categoria, REPLACE(CAST(a.Valor AS VARCHAR), '.', ',') as ValorEsocial, REPLACE(CAST(a.ValorFortes AS VARCHAR), '.', ',') as ValorFortes, CASE WHEN a.Valor = a.ValorFortes THEN 'OK' ELSE 'DIFERENCA' END as CheckList FROM ES_CS_CP_BASE a LEFT JOIN EPG b ON (b.CPF = a.CPF AND b.EMP_Codigo = a.EMP_Codigo AND b.DtRescisao IS NULL) LEFT JOIN EMP c ON c.Codigo = a.EMP_Codigo WHERE a.TipoValor = '21' AND a.PeriodoApuracao BETWEEN FORMAT(DATEADD(MONTH, -12, GETDATE()), 'yyyyMM') AND FORMAT(GETDATE(), 'yyyyMM')" queryout "C:\Fortes\script_super\HSCSLFortesACDemonstrativos.csv" -c -t; -T -S MCPFORTESAC\SQLEXPRESSFORTES -a 512 

REM Copiar arquivo para a pasta de rede
copy "C:\Fortes\script_super\HSCSLFortesACDemonstrativos.csv" "\\10.20.50.60\weknow\FortesDemonstrativos\HSCSLFortesACDemonstrativos.csv"

REM Exibe uma mensagem de conclusão
echo Exportacao concluida com sucesso!

timeout /t 5 /nobreak
